categories:
  - name: "아메리카노"
    items:
      - name: "카카오 아메리카노"
        image: "/images/menu/69265e94c78fa.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "진한 아메리카노"
        image: "/images/menu/69265dfb42630.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "고소한 아메리카노"
        image: "/images/menu/69265de66bc21.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "화사한 아메리카노"
        image: "/images/menu/69265eaade1ee.png"
        options:
          temperature: ["Hot", "Ice"]

  - name: "커피"
    items:
      - name: "더고소한 만잔라떼"
        image: "/images/menu/692663a181203.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "카페 라떼"
        image: "/images/menu/6926643c9058b.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "카카오 라떼"
        image: "/images/menu/6926642d8fe8f.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "크림블랙"
        image: "/images/menu/692664a81103b.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "레몬토닉프레소"
        image: "/images/menu/692663df4b645.png"
        options: {}
      - name: "크런치마시멜로라떼"
        image: "/images/menu/6926647e81783.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "버터스카치크림라떼"
        image: "/images/menu/692664098c032.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "모카 라떼"
        image: "/images/menu/692663eb86c9c.png"
        options:
          temperature: ["Hot", "Ice"]

  - name: "디카페인"
    items:
      - name: "디카페인 콜드브루 아메리카노"
        image: "/images/menu/69265b90d49af.png"
        options:
          temperature: ["Ice"]
      - name: "디카페인 카카오 아메리카노"
        image: "/images/menu/6927bf67353d8.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "디카페인 더고소한만잔라떼"
        image: "/images/menu/69265b08be6ca.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "디카페인 카페라떼"
        image: "/images/menu/69265b63ab224.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "디카페인 크림블랙"
        image: "/images/menu/69265bc49cfa1.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "디카페인 버터스카치 크림라떼"
        image: "/images/menu/69265bfe117e9.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "디카페인 크런치 마시멜로라떼"
        image: "/images/menu/69265ba83a0dd.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "디카페인 모카라떼"
        image: "/images/menu/69265b2761cdd.png"
        options:
          temperature: ["Hot", "Ice"]

  - name: "논커피"
    items:
      - name: "리얼딸기라떼"
        image: "/images/menu/692656fd3a7d5.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "얼그레이 밀크티"
        image: "/images/menu/6926599b478f9.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "초콜릿 라떼"
        image: "/images/menu/69265a8a84611.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "말차 라떼"
        image: "/images/menu/692657554eefc.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "방앗간미숫가루"
        image: "/images/menu/692657a487ca5.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "크런치 마시멜로 솔티초코"
        image: "/images/menu/69265ab4cc38b.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "소복고구마라떼"
        image: "/images/menu/692657b1a59c7.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "미니애플망고주스"
        image: "/images/menu/692657954203e.png"
        options: {}

  - name: "블렌디드"
    items:
      - name: "밀크쉐이크"
        image: "/images/menu/69265cd791828.png"
        options: {}
      - name: "초코스무디"
        image: "/images/menu/69265d4f90d57.png"
        options: {}
      - name: "말차스무디"
        image: "/images/menu/69265c721cac5.png"
        options: {}
      - name: "코코넛칩스무디"
        image: "/images/menu/69265d7a912a9.png"
        options: {}
      - name: "캔디소다 스무디"
        image: "/images/menu/69265d6de2f41.png"
        options: {}
      - name: "플레인요거트스무디"
        image: "/images/menu/69265da09674a.png"
        options: {}
      - name: "블루베리요거트스무디"
        image: "/images/menu/69265cf8db0cc.png"
        options: {}
      - name: "망고요거트스무디"
        image: "/images/menu/69265cb19586b.png"
        options: {}

  - name: "티"
    items:
      - name: "토마토아이스티"
        image: "/images/menu/6926666a8f87b.png"
        options: {}
      - name: "리치캐모마일"
        image: "/images/menu/6926656ba5de2.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "블루베리 팬지꽃차"
        image: "/images/menu/69266584404c4.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "레몬메리골드꽃차"
        image: "/images/menu/692665070a35a.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "코코 자몽홍차"
        image: "/images/menu/692666286a30a.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "코코 레몬홍차"
        image: "/images/menu/6926661d59ba1.png"
        options:
          temperature: ["Hot", "Ice"]
      - name: "복숭아 아이스티"
        image: "/images/menu/6926657549426.png"
        options: {}
      - name: "생강꿀티"
        image: "/images/menu/6926659b7e871.png"
        options:
          temperature: ["Hot"]
